import User, { USER_ROLES, TEACHER_APPROVAL_STATUS } from '../models/User.js';

//@desc   Lấy tất cả người dùng (Có hỗ trợ lọc theo role)
//@route  GET /api/admin/users
//@access Private/Admin
export const getUsers = async (req, res, next) => {
  try {
    const normalizedRole = typeof req.query.role === 'string'
      ? req.query.role.toUpperCase()
      : null;
    const query = normalizedRole ? { role: normalizedRole } : {};

    const users = await User.find(query).select('-password').sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: users.length,
      data: users,
    });
  } catch (error) {
    next(error);
  }
};

//@desc   Xem chi tiết 1 tài khoản
//@route  GET /api/admin/users/:id
//@access Private/Admin
export const getUserById = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id).select('-password');

    if (!user) {
      return res.status(404).json({ success: false, error: 'Không tìm thấy người dùng' });
    }

    res.status(200).json({
      success: true,
      data: user,
    });
  } catch (error) {
    next(error);
  }
};

//@desc   Thêm mới người dùng (Mật khẩu tự động tạo dựa trên Role)
//@route  POST /api/admin/users
//@access Private/Admin
export const createUser = async (req, res, next) => {
  try {
    const { fullName, email, role } = req.body;

    // Kiểm tra xem email đã tồn tại chưa
    const userExists = await User.findOne({ email });
    if (userExists) {
      return res.status(400).json({ success: false, error: 'Email đã được sử dụng trong hệ thống' });
    }

    // Chuẩn hóa role, mặc định là LEARNER nếu không truyền
    const userRole = role ? role.toUpperCase() : USER_ROLES.LEARNER;

    // Tự động tạo mật khẩu: Ví dụ Role là TEACHER -> Mật khẩu là: Teacher@123
    const autoPassword = `${userRole.charAt(0).toUpperCase() + userRole.slice(1).toLowerCase()}@123`;

    // Tạo người dùng
    const user = await User.create({
      fullName,
      email,
      password: autoPassword,
      role: userRole,
      teacherApprovalStatus: TEACHER_APPROVAL_STATUS.APPROVED 
    });

    res.status(201).json({
      success: true,
      message: 'Tạo tài khoản thành công',
      data: {
        _id: user._id,
        fullName: user.fullName,
        email: user.email,
        role: user.role,
        teacherApprovalStatus: user.teacherApprovalStatus,
        autoGeneratedPassword: autoPassword 
      }
    });
  } catch (error) {
    next(error);
  }
};

//@desc   Cập nhật thông tin tài khoản (Vai trò, Trạng thái hoạt động, Duyệt giáo viên)
//@route  PUT /api/admin/users/:id
//@access Private/Admin
export const updateUser = async (req, res, next) => {
  try {
    const { role, isActive, teacherApprovalStatus } = req.body;
    const user = await User.findById(req.params.id);

    if (!user) {
      return res.status(404).json({ 
        success: false, 
        error: 'Không tìm thấy người dùng' 
      });
    }

    // 1. Khóa / Mở khóa tài khoản
    if (isActive !== undefined) {
      user.isActive = isActive;
    }

    // 2. Cập nhật vai trò (Role)
    if (role) {
      const upperRole = role.toUpperCase();
      if (Object.values(USER_ROLES).includes(upperRole)) {
        user.role = upperRole;
        
        // Logic phụ: Nếu giáng cấp từ Giáo viên xuống Học viên, reset lại trạng thái duyệt
        if (upperRole !== USER_ROLES.TEACHER) {
            user.teacherApprovalStatus = TEACHER_APPROVAL_STATUS.APPROVED;
        } else if (upperRole === USER_ROLES.TEACHER && !user.teacherApprovalStatus) {
            user.teacherApprovalStatus = TEACHER_APPROVAL_STATUS.PENDING;
        }
      } else {
        return res.status(400).json({ success: false, error: 'Vai trò không hợp lệ' });
      }
    }

    // 3. Cập nhật trạng thái duyệt hồ sơ
    if (teacherApprovalStatus) {
      if (user.role !== USER_ROLES.TEACHER) {
        return res.status(400).json({
          success: false,
          error: 'Tính năng duyệt hồ sơ (teacherApprovalStatus) chỉ áp dụng cho Giáo viên.'
        });
      }
      if (Object.values(TEACHER_APPROVAL_STATUS).includes(teacherApprovalStatus)) {
        user.teacherApprovalStatus = teacherApprovalStatus;
      }
    }

    await user.save(); // pre-save middleware sẽ KHÔNG mã hóa lại pass vì pass không bị sửa đổi

    res.status(200).json({
      success: true,
      message: 'Cập nhật tài khoản thành công',
      data: {
        _id: user._id,
        fullName: user.fullName,
        role: user.role,
        isActive: user.isActive,
        teacherApprovalStatus: user.teacherApprovalStatus 
      },
    });
  } catch (error) {
    next(error);
  }
};

//@desc   Xóa tài khoản
//@route  DELETE /api/admin/users/:id
//@access Private/Admin
export const deleteUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id);

    if (!user) {
      return res.status(404).json({ success: false, error: 'Không tìm thấy người dùng' });
    }

    await user.deleteOne();

    res.status(200).json({
      success: true,
      message: 'Đã xóa tài khoản thành công',
    });
  } catch (error) {
    next(error);
  }
};